//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEKA_APP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KaydedilenKullaniciAdi {
            get {
                return ((string)(this["KaydedilenKullaniciAdi"]));
            }
            set {
                this["KaydedilenKullaniciAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KaydedilenSifre {
            get {
                return ((string)(this["KaydedilenSifre"]));
            }
            set {
                this["KaydedilenSifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BeniHatirla {
            get {
                return ((bool)(this["BeniHatirla"]));
            }
            set {
                this["BeniHatirla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KlasorYolu {
            get {
                return ((string)(this["KlasorYolu"]));
            }
            set {
                this["KlasorYolu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OdemeSartlariGridSettings {
            get {
                return ((string)(this["OdemeSartlariGridSettings"]));
            }
            set {
                this["OdemeSartlariGridSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SutunSirasiOdemeSartlari {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SutunSirasiOdemeSartlari"]));
            }
            set {
                this["SutunSirasiOdemeSartlari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SutunSirasiMusteriler {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SutunSirasiMusteriler"]));
            }
            set {
                this["SutunSirasiMusteriler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SutunSirasiTeminatMektuplari {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SutunSirasiTeminatMektuplari"]));
            }
            set {
                this["SutunSirasiTeminatMektuplari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SutunGenislikOdemeSartlariListe {
            get {
                return ((string)(this["SutunGenislikOdemeSartlariListe"]));
            }
            set {
                this["SutunGenislikOdemeSartlariListe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SutunGenislikTeminatMektuplari {
            get {
                return ((string)(this["SutunGenislikTeminatMektuplari"]));
            }
            set {
                this["SutunGenislikTeminatMektuplari"] = value;
            }
        }
    }
}
